--------------------------------------------------------
--  Arquivo criado - Quinta-feira-Maio-05-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PRODUTO
--------------------------------------------------------

  CREATE TABLE "HR"."PRODUTO" 
   (	"PROD_ID" NUMBER(*,0), 
	"TP_ID" NUMBER(*,0), 
	"PROD_NOME" VARCHAR2(100 BYTE), 
	"PROD_VALOR" NUMBER(6,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ;
REM INSERTING into HR.PRODUTO
SET DEFINE OFF;
Insert into HR.PRODUTO (PROD_ID,TP_ID,PROD_NOME,PROD_VALOR) values ('1','1','HAVAIANAS','20,3');
Insert into HR.PRODUTO (PROD_ID,TP_ID,PROD_NOME,PROD_VALOR) values ('2','1','MORMAI','22,3');
Insert into HR.PRODUTO (PROD_ID,TP_ID,PROD_NOME,PROD_VALOR) values ('3','3','NIKE 97','1000');
Insert into HR.PRODUTO (PROD_ID,TP_ID,PROD_NOME,PROD_VALOR) values ('4','3','ADIDAS NMD','1000');
Insert into HR.PRODUTO (PROD_ID,TP_ID,PROD_NOME,PROD_VALOR) values ('5','5','SANTA LOLA 15 CM','200');
Insert into HR.PRODUTO (PROD_ID,TP_ID,PROD_NOME,PROD_VALOR) values ('6','6','AREZZO BEJE','350');
Insert into HR.PRODUTO (PROD_ID,TP_ID,PROD_NOME,PROD_VALOR) values ('7','6','AREZZO PRETA','350');
--------------------------------------------------------
--  DDL for Index PK_PROD_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."PK_PROD_ID" ON "HR"."PRODUTO" ("PROD_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ;
--------------------------------------------------------
--  DDL for Index UK_PROD_NOME
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."UK_PROD_NOME" ON "HR"."PRODUTO" ("PROD_NOME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ;
--------------------------------------------------------
--  DDL for Trigger PRODUTO_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "HR"."PRODUTO_TRG" 
BEFORE INSERT ON PRODUTO 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.PROD_ID IS NULL THEN
      SELECT PRODUTO_SEQ.NEXTVAL INTO :NEW.PROD_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "HR"."PRODUTO_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table PRODUTO
--------------------------------------------------------

  ALTER TABLE "HR"."PRODUTO" MODIFY ("PROD_NOME" CONSTRAINT "PROD_NOME_NOT_NULL" NOT NULL ENABLE);
  ALTER TABLE "HR"."PRODUTO" MODIFY ("PROD_VALOR" CONSTRAINT "PROD_VALOR_NOT_NULL" NOT NULL ENABLE);
  ALTER TABLE "HR"."PRODUTO" ADD CONSTRAINT "PK_PROD_ID" PRIMARY KEY ("PROD_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX"  ENABLE;
  ALTER TABLE "HR"."PRODUTO" ADD CONSTRAINT "UK_PROD_NOME" UNIQUE ("PROD_NOME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PRODUTO
--------------------------------------------------------

  ALTER TABLE "HR"."PRODUTO" ADD CONSTRAINT "FK_TP_ID" FOREIGN KEY ("TP_ID")
	  REFERENCES "HR"."TIPO_PRODUTO" ("TP_ID") ENABLE;
